name: Auto-generate PR from Issues using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main
    # Check if the label is 'aider'
    if: github.event.label.name == 'aider'
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
      model: "anthropic/claude-3-5-sonnet-20241022"
    secrets: 
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
